language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
    - node_modules



install:
  # Update npm
  - npm install -g npm@2.9.1
  - npm --version
  # Check the size of caches
  - du -sh ./node_modules || true
  # Install npm dependecies
  - npm install



